import type { GardenState, Plant, Planting, PlanObject } from "./types";

export const MONTHS = [
  "Янв",
  "Фев",
  "Мар",
  "Апр",
  "Май",
  "Июн",
  "Июл",
  "Авг",
  "Сен",
  "Окт",
  "Ноя",
  "Дек",
];

export const PLAN_COLORS = {
  house: "#c8b29d",
  greenhouse: "#b8d7c4",
  building: "#bea995",
  bed: "#b98a5d",
  flowerbed: "#d8a8b4",
  lawn: "#b9d49a",
  pond: "#9fcbd0",
  path: "#d8cbb7",
  tree: "#6f9860",
  shrub: "#88a86e",
  zone: "#d7cda6",
} as const;

export const DEFAULT_PLAN_OBJECTS: PlanObject[] = [
  {
    id: "house-1",
    type: "house",
    label: "Дом",
    x: 82,
    y: 66,
    width: 176,
    height: 126,
    rotation: 0,
    color: PLAN_COLORS.house,
    season: "permanent",
  },
  {
    id: "path-1",
    type: "path",
    label: "Главная дорожка",
    x: 286,
    y: 48,
    width: 48,
    height: 442,
    rotation: 0,
    color: PLAN_COLORS.path,
    season: "permanent",
  },
  {
    id: "greenhouse-1",
    type: "greenhouse",
    label: "Теплица",
    x: 388,
    y: 72,
    width: 164,
    height: 88,
    rotation: 0,
    color: PLAN_COLORS.greenhouse,
    season: "permanent",
  },
  {
    id: "bed-1",
    type: "bed",
    label: "Грядка у теплицы",
    x: 386,
    y: 194,
    width: 176,
    height: 56,
    rotation: 0,
    color: PLAN_COLORS.bed,
    season: "2026",
  },
  {
    id: "bed-2",
    type: "bed",
    label: "Тёплая грядка",
    x: 386,
    y: 274,
    width: 176,
    height: 56,
    rotation: 0,
    color: "#a97b50",
    season: "2026",
  },
  {
    id: "lawn-1",
    type: "lawn",
    label: "Лужайка",
    x: 84,
    y: 238,
    width: 166,
    height: 190,
    rotation: 0,
    color: PLAN_COLORS.lawn,
    season: "permanent",
  },
  {
    id: "flowerbed-1",
    type: "flowerbed",
    label: "Розовый миксбордер",
    x: 588,
    y: 74,
    width: 138,
    height: 206,
    rotation: 0,
    color: PLAN_COLORS.flowerbed,
    season: "permanent",
  },
  {
    id: "pond-1",
    type: "pond",
    label: "Пруд",
    x: 586,
    y: 346,
    width: 124,
    height: 94,
    rotation: -8,
    color: PLAN_COLORS.pond,
    season: "permanent",
  },
  {
    id: "tree-1",
    type: "tree",
    label: "Яблоня Антоновка",
    x: 98,
    y: 444,
    width: 62,
    height: 62,
    rotation: 0,
    color: PLAN_COLORS.tree,
    season: "permanent",
  },
  {
    id: "tree-2",
    type: "tree",
    label: "Вишня",
    x: 184,
    y: 446,
    width: 52,
    height: 52,
    rotation: 0,
    color: "#779e65",
    season: "permanent",
  },
];

export const INITIAL_PLANTS: Plant[] = [
  {
    id: "tomato",
    name: "Томат",
    latinName: "Solanum lycopersicum",
    kind: "Овощи",
    zone: "Теплица",
    countLabel: "8 растений",
    careCoverage: "full",
    stage: "Плодоношение",
  },
  {
    id: "cucumber",
    name: "Огурец",
    latinName: "Cucumis sativus",
    kind: "Овощи",
    zone: "Теплица",
    countLabel: "6 растений",
    careCoverage: "full",
    stage: "Плодоношение",
  },
  {
    id: "apple-antonovka",
    name: "Яблоня Антоновка",
    latinName: "Malus domestica",
    kind: "Плодовые",
    zone: "Плодовый сад",
    countLabel: "1 дерево · 7 лет",
    bloomStart: 5,
    bloomEnd: 5,
    bloomColor: "#ead7dd",
    careCoverage: "full",
    stage: "Налив плодов",
  },
  {
    id: "cherry",
    name: "Вишня",
    latinName: "Prunus cerasus",
    kind: "Плодовые",
    zone: "Плодовый сад",
    countLabel: "1 дерево · около 5 лет",
    bloomStart: 5,
    bloomEnd: 6,
    bloomColor: "#f0dce2",
    careCoverage: "full",
    stage: "После сбора урожая",
  },
  {
    id: "hydrangea",
    name: "Гортензия метельчатая",
    latinName: "Hydrangea paniculata",
    kind: "Декоративные",
    zone: "Розовый миксбордер",
    countLabel: "3 куста · 4 года",
    bloomStart: 7,
    bloomEnd: 10,
    bloomColor: "#e0b4c3",
    careCoverage: "full",
    stage: "Цветение",
  },
  {
    id: "echinacea",
    name: "Эхинацея пурпурная",
    latinName: "Echinacea purpurea",
    kind: "Декоративные",
    zone: "Розовый миксбордер",
    countLabel: "Группа · 9 растений",
    bloomStart: 7,
    bloomEnd: 9,
    bloomColor: "#c87c9a",
    careCoverage: "basic",
    stage: "Цветение",
  },
];

export const INITIAL_PLANTINGS: Planting[] = [
  {
    id: "planting-tomato",
    plantId: "tomato",
    planObjectId: "greenhouse-1",
    mode: "area",
    x: 430,
    y: 108,
    quantity: 8,
    season: "2026",
  },
  {
    id: "planting-cucumber",
    plantId: "cucumber",
    planObjectId: "greenhouse-1",
    mode: "area",
    x: 505,
    y: 128,
    quantity: 6,
    season: "2026",
  },
  {
    id: "planting-apple",
    plantId: "apple-antonovka",
    planObjectId: "tree-1",
    mode: "point",
    x: 129,
    y: 475,
    quantity: 1,
    season: "permanent",
  },
  {
    id: "planting-cherry",
    plantId: "cherry",
    planObjectId: "tree-2",
    mode: "point",
    x: 210,
    y: 472,
    quantity: 1,
    season: "permanent",
  },
  {
    id: "planting-hydrangea",
    plantId: "hydrangea",
    planObjectId: "flowerbed-1",
    mode: "group",
    x: 625,
    y: 128,
    quantity: 3,
    season: "permanent",
  },
  {
    id: "planting-echinacea",
    plantId: "echinacea",
    planObjectId: "flowerbed-1",
    mode: "group",
    x: 682,
    y: 218,
    quantity: 9,
    season: "permanent",
  },
];

const CATALOG_ROWS: Array<
  [string, string, Plant["kind"], number?, number?, string?]
> = [
  ["Томат", "Solanum lycopersicum", "Овощи"],
  ["Огурец", "Cucumis sativus", "Овощи"],
  ["Перец сладкий", "Capsicum annuum", "Овощи"],
  ["Баклажан", "Solanum melongena", "Овощи"],
  ["Картофель", "Solanum tuberosum", "Овощи"],
  ["Морковь", "Daucus carota", "Овощи"],
  ["Свёкла", "Beta vulgaris", "Овощи"],
  ["Капуста белокочанная", "Brassica oleracea", "Овощи"],
  ["Кабачок", "Cucurbita pepo", "Овощи"],
  ["Тыква", "Cucurbita maxima", "Овощи"],
  ["Горох", "Pisum sativum", "Овощи"],
  ["Фасоль", "Phaseolus vulgaris", "Овощи"],
  ["Лук репчатый", "Allium cepa", "Овощи"],
  ["Чеснок", "Allium sativum", "Овощи"],
  ["Редис", "Raphanus sativus", "Овощи"],
  ["Салат", "Lactuca sativa", "Овощи"],
  ["Укроп", "Anethum graveolens", "Овощи"],
  ["Петрушка", "Petroselinum crispum", "Овощи"],
  ["Яблоня", "Malus domestica", "Плодовые", 5, 5, "#ead7dd"],
  ["Груша", "Pyrus communis", "Плодовые", 5, 5, "#edf0da"],
  ["Вишня", "Prunus cerasus", "Плодовые", 5, 6, "#f0dce2"],
  ["Слива", "Prunus domestica", "Плодовые", 5, 5, "#eee0ed"],
  ["Смородина чёрная", "Ribes nigrum", "Плодовые", 5, 5, "#dfe6bd"],
  ["Смородина красная", "Ribes rubrum", "Плодовые", 5, 5, "#e9d9d7"],
  ["Крыжовник", "Ribes uva-crispa", "Плодовые", 5, 5, "#dfe2b7"],
  ["Малина", "Rubus idaeus", "Плодовые", 6, 7, "#e4bdca"],
  ["Земляника садовая", "Fragaria × ananassa", "Плодовые", 5, 6, "#f0e5e5"],
  ["Облепиха", "Hippophae rhamnoides", "Плодовые", 4, 5, "#e9cf88"],
  ["Жимолость съедобная", "Lonicera caerulea", "Плодовые", 5, 5, "#e8e2ca"],
  ["Гортензия метельчатая", "Hydrangea paniculata", "Декоративные", 7, 10, "#e0b4c3"],
  ["Эхинацея пурпурная", "Echinacea purpurea", "Декоративные", 7, 9, "#c87c9a"],
  ["Пион молочноцветковый", "Paeonia lactiflora", "Декоративные", 6, 7, "#d68ea7"],
  ["Роза парковая", "Rosa", "Декоративные", 6, 9, "#cb6e79"],
  ["Флокс метельчатый", "Phlox paniculata", "Декоративные", 7, 9, "#b991c4"],
  ["Астильба", "Astilbe", "Декоративные", 6, 8, "#d28aa8"],
  ["Хоста", "Hosta", "Декоративные", 7, 8, "#d9cbdc"],
  ["Ирис сибирский", "Iris sibirica", "Декоративные", 6, 7, "#8385b8"],
  ["Лилейник", "Hemerocallis", "Декоративные", 6, 8, "#d79866"],
  ["Лаванда узколистная", "Lavandula angustifolia", "Декоративные", 7, 8, "#9a85bc"],
  ["Дельфиниум", "Delphinium", "Декоративные", 6, 8, "#7886bd"],
  ["Рудбекия", "Rudbeckia", "Декоративные", 7, 10, "#d9a83c"],
  ["Астра новобельгийская", "Symphyotrichum novi-belgii", "Декоративные", 8, 10, "#a084bd"],
  ["Крокус", "Crocus", "Декоративные", 3, 4, "#9a78bc"],
  ["Нарцисс", "Narcissus", "Декоративные", 4, 5, "#e6ce68"],
  ["Тюльпан", "Tulipa", "Декоративные", 4, 5, "#d67571"],
  ["Сирень обыкновенная", "Syringa vulgaris", "Декоративные", 5, 6, "#b99ac4"],
  ["Чубушник", "Philadelphus coronarius", "Декоративные", 6, 7, "#e9e4d5"],
  ["Спирея японская", "Spiraea japonica", "Декоративные", 6, 8, "#d5899e"],
];

export const CATALOG: Plant[] = CATALOG_ROWS.map(
  ([name, latinName, kind, bloomStart, bloomEnd, bloomColor], index) => ({
    id: `catalog-${index + 1}`,
    name,
    latinName,
    kind,
    zone: "Не размещено",
    countLabel: "Нет на участке",
    bloomStart,
    bloomEnd,
    bloomColor,
    careCoverage: index < 30 ? "full" : "basic",
    stage: "Не указано",
  }),
);

export const INITIAL_STATE: GardenState = {
  revision: 1,
  lastAnalyzedAt: "сегодня, 06:12",
  tasks: [
    {
      id: "water-greenhouse",
      title: "Полить теплицу",
      zone: "Теплица",
      time: "12 мин",
      window: "до 09:30",
      why: "После тёплой ночи верхний слой почвы подсох. Дождь ожидается только вечером и не увлажнит грунт в теплице.",
      priority: "high",
      risk: "low",
      status: "todo",
      completedItems: 0,
      totalItems: 2,
      ruleId: "watering.greenhouse.v3",
    },
    {
      id: "harvest-cucumber",
      title: "Собрать огурцы",
      zone: "Теплица",
      time: "8 мин",
      window: "сегодня",
      why: "Регулярный сбор поддерживает образование новых плодов. Последняя отметка была три дня назад.",
      priority: "normal",
      risk: "low",
      status: "todo",
      completedItems: 0,
      totalItems: 1,
      ruleId: "harvest.cucumber.v2",
    },
    {
      id: "check-tomatoes",
      title: "Осмотреть томаты",
      zone: "Теплица",
      time: "10 мин",
      window: "сегодня–завтра",
      why: "После периода высокой влажности полезно проверить нижние листья. Это наблюдение, не рекомендация по обработке.",
      priority: "normal",
      risk: "low",
      status: "todo",
      completedItems: 0,
      totalItems: 8,
      ruleId: "observe.tomato.humidity.v4",
    },
    {
      id: "deadhead-echinacea",
      title: "Убрать отцветшие соцветия",
      zone: "Розовый миксбордер",
      time: "15 мин",
      window: "до 30 июля",
      why: "Часть эхинацей завершает первую волну цветения. Удаление сухих корзинок продлит декоративность.",
      priority: "low",
      risk: "low",
      status: "todo",
      completedItems: 0,
      totalItems: 1,
      ruleId: "deadhead.echinacea.v2",
    },
  ],
  planObjects: DEFAULT_PLAN_OBJECTS,
  plants: INITIAL_PLANTS,
  plantings: INITIAL_PLANTINGS,
  journal: [
    {
      id: "journal-1",
      date: "26 июля",
      title: "Собрали первую корзину томатов",
      note: "Антоновка пока без падалицы. В теплице проветрили обе двери.",
      zone: "Теплица",
    },
    {
      id: "journal-2",
      date: "23 июля",
      title: "Зацвела гортензия",
      note: "Подтвердили стадию цветения — календарь обновлён.",
      zone: "Розовый миксбордер",
    },
  ],
};
